---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: "10:00"
      timezone: "Asia/Tokyo"
    labels:
      - github-actions-update
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'chore(github-actions): '

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: "10:00"
      timezone: "Asia/Tokyo"
    labels:
      - pnpm-update
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: 'chore(pnpm): '
