---
name: Perl test for kalaclista

on:
  pull_request:
    paths:
      - ".github/workflows/perl-test.yml"
      - "bin/**"
      - "lib/**"
      - "t/**"
      - "Makefile"
      - "cpanfile"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bc \
            cmark-gfm \
            coreutils \
            esbuild \
            findutils \
            imagemagick \
            make \
            neovim \
            neovim-runtime \
            openssl \
            sed \
            webp \
          # done

      - name: Concat cpanfile
        run:
          cat cpanfile app/cpanfile >cpanfile.test
      # perl environment
      - uses: shogo82148/actions-setup-perl@3d69de4658363aa141f2d961d0f4a17584a36150 # v1.28.0
        with:
          perl-version: '5.38'
          install-modules-with: cpm
          install-modules-args: '-L extlib --cpanfile=cpanfile.test'

      # pnpm environment
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - uses: pnpm/action-setup@ebcfd6995dade4b0104ac774445cef8b3b4635b0 # v2.4.0-dev
        with:
          version: 8
          run_install: true

      # testing envionment
      - name: CI tests
        run: |
          # set environment variables
          export PATH=$(pwd)/extlib/bin:$PATH
          export PERL5LIB=$(pwd)/extlib/lib/perl5:$(pwd)/app/lib:$(pwd)/lib
          export IN_PERL_SHELL=1

          # run ci test
          make ci
