---
name: Perl test for kalaclista

on:
  pull_request:
    paths:
      - ".github/workflows/perl-test.yml"
      - "bin/**"
      - "lib/**"
      - "t/**"
      - "Makefile"
      - "cpanfile"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.38'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmark-gfm \
            coreutils \
            esbuild \
            findutils \
            imagemagick \
            make \
            nodejs \
            openssl \
            sed \
            webp

          cpm install -L extlib --cpanfile app/cpanfile
          cpm install -L extlib --cpanfile cpanfile
      - name: Run tests
        run: |
          export PATH=$(pwd)/extlib/bin:$PATH
          export PERL5LIB=$(pwd)/extlib/lib/perl5:$(pwd)/app/lib:$(pwd)/lib
          export IN_PERL_SHELL=1

          make ci
