---
name: Perl test for kalaclista

on:
  pull_request:
    branches: ['*']
    paths:
      - ".github/workflows/perl-test.yml"
      - "app/**"
      - "bin/**"
      - "lib/**"
      - "t/**"
      - "Makefile"
      - "cpanfile"
      - "package.json"
      - "pnpm-lock.yaml"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          submodules: true
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bc \
            cmark-gfm \
            coreutils \
            esbuild \
            findutils \
            imagemagick \
            libidn-dev \
            make \
            minify \
            neovim \
            neovim-runtime \
            openssl \
            sed \
            webp \
          # done
      - name: Install binary commands
        run: |
          curl -L https://github.com/tdewolff/minify/releases/download/v2.20.37/checksums.txt | grep 'linux_amd64.tar.gz' >checksums.txt
          curl -LO https://github.com/tdewolff/minify/releases/download/v2.20.37/minify_linux_amd64.tar.gz
          sha256sum -c checksums.txt
          tar -zxvf minify_linux_amd64.tar.gz
          sudo cp minify /usr/bin/minify
          sudo chmod +x /usr/bin/minify

      - name: Concat cpanfile
        run: |
          cat cpanfile app/cpanfile >cpanfile.test
          mv cpanfile.test cpanfile
      # perl environment
      - uses: shogo82148/actions-setup-perl@9c1eca9952ccc07f9ca4a2097b63df93d9d138e9 # v1.31.3
        with:
          perl-version: '5.38'
          install-modules-with: cpm

      # pnpm environment
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v2.4.0-dev
        with:
          version: 8
          run_install: true

      # testing envionment
      - name: CI tests
        run: |
          # set environment variables
          export PATH=$(pwd)/local/bin:$PATH
          export PERL5LIB=$(pwd)/local/lib/perl5:$(pwd)/app/lib:$(pwd)/lib:$PERL5LIB
          export IN_PERL_SHELL=1
          export TERM=xterm-256color

          # run ci test
          make ci
