---
name: Perl test for kalaclista

on:
  pull_request:
    paths:
      - ".github/workflows/perl-test.yml"
      - "bin/**"
      - "lib/**"
      - "t/**"
      - "Makefile"
      - "cpanfile"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # runner environment
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: true
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            bc \
            cmark-gfm \
            coreutils \
            esbuild \
            findutils \
            imagemagick \
            libidn-dev \
            make \
            minify \
            neovim \
            neovim-runtime \
            openssl \
            sed \
            webp \
          # done
      - name: Install binary commands
        run: |
          curl -L https://github.com/tdewolff/minify/releases/download/v2.20.19/checksums.txt | grep 'linux_amd64.tar.gz' >checksums.txt
          curl -LO https://github.com/tdewolff/minify/releases/download/v2.20.19/minify_linux_amd64.tar.gz
          sha256sum -c checksums.txt
          tar -zxvf minify_linux_amd64.tar.gz
          sudo cp minify /usr/bin/minify
          sudo chmod +x /usr/bin/minify

      - name: Concat cpanfile
        run:
          cat cpanfile app/cpanfile >cpanfile.test
      # perl environment
      - uses: shogo82148/actions-setup-perl@28eae78d12c2bba1163aec45d123f6d9228bc307 # v1.29.0
        with:
          perl-version: '5.38'
          install-modules-with: cpm
          install-modules-args: '-L extlib --cpanfile=cpanfile.test'

      # pnpm environment
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v2.4.0-dev
        with:
          version: 8
          run_install: true

      # testing envionment
      - name: CI tests
        run: |
          # set environment variables
          export PATH=$(pwd)/extlib/bin:$PATH
          export PERL5LIB=$(pwd)/extlib/lib/perl5:$(pwd)/app/lib:$(pwd)/lib:$PERL5LIB
          export IN_PERL_SHELL=1

          # run ci test
          make ci
